REVOKE EXECUTE ON FUNCTION public.approve_late_reason(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.reject_late_reason(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.submit_late_reason(uuid, text, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.approve_unlock_letter(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.reject_unlock_letter(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_unlock_letter_document(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.submit_unlock_letter(uuid, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.unlock_account(uuid, uuid, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.check_attendance_thresholds(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_attendance_violation(uuid, uuid, date, text, text, text, uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_attendance_discipline_config() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_attendance_discipline_dashboard_stats(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_attendance_discipline_employee_rows(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_monthly_violation_count(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_rolling_3month_violation_count(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.is_discipline_admin() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.approve_late_reason(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_late_reason(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_late_reason(uuid, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.approve_unlock_letter(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.reject_unlock_letter(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_unlock_letter_document(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_unlock_letter(uuid, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unlock_account(uuid, uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_attendance_discipline_config() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_attendance_discipline_dashboard_stats(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_attendance_discipline_employee_rows(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_monthly_violation_count(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_rolling_3month_violation_count(uuid, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_discipline_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_attendance_thresholds(uuid, date) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_attendance_violation(uuid, uuid, date, text, text, text, uuid) TO service_role;